### ISSUE TITLE
Plugin does not scope CSS container queries

### ISSUE THREAD

**Issue by arw6329** [cmseguin/rollup-plugin-react-scoped-css#67]
The plugin does not properly scope CSS [container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/@container), which are at-rules similar to media queries that allow you to apply rulesets based on the size of a parent element with a containment context.

For example, these two components:

MyElem.tsx:

```tsx
import "./MyElem.scoped.css"

const MyElem = () => {
    return (
        <span>Hello</span>
    )
}

export default MyElem

```

MyElem.scoped.css:

```css
span {
    text-decoration: underline;
}

@container abc (min-width: 100px) {
    span {
        color: red;
    }
}
```

Parent.tsx:

```tsx
import MyElem from "./MyElem"
import "./Parent.scoped.css"

const Parent = () => {
    return (
        <div>
            <span>Parent elem</span>
            <MyElem />
        </div>
    )
}

export default Parent
```

Parent.scoped.css:

```css
div {
    container-type: inline-size;
    container-name: abc;
}
```

result in the `color: red` rule being applied globally instead of being scoped like the `text-decoration: underline` rule:

![Image](https://github.com/user-attachments/assets/4579219a-bd1d-473a-a85b-42894f7c7658)

This is annoying because not only does the scoping not work, but it breaks common uses of container queries if you use the same selector both inside and outside of a container query because of specificity. For example, here, the `flex-direction: column` will never be applied because the outer ruleset will get the [data-*] scoper and be more specific:

```css
.my-elem {
    display: flex;
    flex-direction: row;
}

@container (max-width: 100px) {
    .my-elem {
        flex-direction: column;
    }
}
```
